### ISSUE TITLE
Icons Request: DBeaver

### ISSUE THREAD

**Issue by ayron86** [linuxmint/mint-y-icons#260]
https://dbeaver.io/

![image](https://user-images.githubusercontent.com/29458646/89043457-81e17880-d316-11ea-9c54-09765366747f.png)

**Comment by NikoKrause** [comment]
Hey, there's already a beaver icon in Mint-Y, but it's not used, because the application uses a hardcoded path for it's icon.

This means, if you open the `dbeaver.desktop` file in `/usr/share/applications` with a text editor, e.g. xed, you'll find the line:
```
Icon=/usr/share/dbeaver/dbeaver.png
```

It's an absolute path, instead of an icon name. You have to change that line to
```
Icon=beaver
```

There's nothing we can do on our side to change that. The apps developer can decide, if they allow their app icon to be themeable, i.e. being an icon name, or if they want it to look the same no matter which icon theme the user is using, i.e. pointing to exact location of the icon (using an absolute path).
