### ISSUE TITLE
Change Firefox colors.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint-y-icons#318]
These color changes are closer to the upstream and keep the Mint-Y style.

![firefox](https://user-images.githubusercontent.com/59381215/193496171-b6599dec-f57d-4dd6-b122-b365b45e6cc9.svg)

**Comment by PHPeon** [comment]
This would be good for nightly

**Comment by luisrguerra** [comment]
I find it very difficult for them to accept this change, it was already very difficult for them to update the firefox logo that was already two generations late. I believe that the ideal would be to use the original logo because it is reasonably good and would be easier to recognize, but they have great resistance to accepting the idea because it would not follow the standards of the Moka theme that has already been discontinued, this theme is inconsistent and as far as I know never had a guidebook on how to make icons.

**Comment by luisrguerra** [comment]
I have already suggested that they use the Papirus theme, which is already very well designed and would match the style of the interface but I don't think they would adopt it.

**Comment by clefebvre** [comment]
The FF icon we're currently using was reviewed and accepted by Mozilla.
