### ISSUE TITLE
[Feature Request] - Add icon to warpinator folder

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint-y-icons#336]
The warpinator folder is currently identical to the newly created folders. 
![sc](https://user-images.githubusercontent.com/68134588/227606926-8a572a62-9199-43cc-91f0-30a721bc4ead.png)

Being a folder that indicates a remarkable place in the system, I think it should have a [symbol](https://github.com/linuxmint/warpinator/blob/19f904e7889477e1cd42a0b0e6669ee9978762cb/data/icons/hicolor/scalable/apps/org.x.Warpinator-symbolic.svg) that distinguishes it.

@SebastJava maybe something like that?
![warpinator folder](https://user-images.githubusercontent.com/68134588/227574694-32b539c0-98ac-40e4-9c2a-1ab181d62e40.png)

**Comment by SebastJava** [comment]
Yep. This looks good. This grey `#4A4A4A` is probably just the right balance between "too much" and "not enough". And it is a good symbol and the size is good, also.

This colored stripe could go away, but that's another discussion, as found somewhere else on https://github.com/linuxmint/

**Comment by haggen88** [comment]
@SebastJava I only took the [symbolic icon](https://github.com/linuxmint/warpinator/blob/19f904e7889477e1cd42a0b0e6669ee9978762cb/data/icons/hicolor/scalable/apps/org.x.Warpinator-symbolic.svg), I changed the scale and the color to the ones that appear [here](https://github.com/linuxmint/mint-y-icons/blob/master/src/places/aqua.svg), I have no idea of the specific design parameters... I leave it in your hands.

**Comment by mtwebster** [comment]
There's one problem with this - how do we get file managers or anything else to apply this icon to the correct folder (or any folder the user might configure Warpinator to use)?

This isn't an official XDG-specification folder where there are functions that apps can use to look up their paths and apply the correct icon, so it will be identified as just another folder.

We could do something in Nemo to lookup what the setting is for the save folder and apply the icon to it, but it'll only work in nemo, not file picker dialogs, any other file managers, Cinnamon, etc... so it's probably not worth it.

**Comment by SebastJava** [comment]
@haggen88 I felt honored to be asked for my feedback on this but I do not have any power here. I do not have a direct access as I am not an official contributor here. My only PRs that got accepted here were just obvious little scripting updates...

@mtwebster I didn't know about that XDG-specification. It sounds serious. This Nemo is already a big complex thing and there are still many bugs to get fixed. So, for sure, I would not even think about adding an extra program or script just for one special icon. Could this Warpinator icon be done the same way as for the downloads and music icons ? If yes, than it's a good idea. Otherwise, please forget it.

**Comment by haggen88** [comment]
> Could this Warpinator icon be done the same way as for the downloads and music icons ?
@mtwebster  I thought it would be something that simple. But apparently it is more complex.
