### ISSUE TITLE
Clipman tray icon missing after Mint Cinnamon 21.2 Victoria update

### ISSUE THREAD

**Issue by luzz-dev** [linuxmint/mint-y-icons#351]
It defaults to the gnome one after the update.
Was the clipman tray icon/action removed from the icon pack?

**Comment by mtwebster** [comment]
No application icons were deliberately removed as far as I know, just action icons.

When I check out clipman, it says it's for wayland - what does it have to do with Cinnamon?

**Comment by mtwebster** [comment]
Where do you get clipman? Like I said, the version I find is for wayland.

**Comment by luzz-dev** [comment]
sudo apt install xfce4-clipman
Maybe I shouldn´t install something that says meat to be used on xfce while using cinnamon?
![image](https://github.com/linuxmint/mint-y-icons/assets/132844414/33a87665-aaa8-4a8d-b779-96fdde98c839)

**Comment by mtwebster** [comment]
It looks for 'clipman' being in the icon theme. That's never been in any Mint themes.

If that fails it resorts to using 'edit-paste' which was one of the action icons removed for Mint 21.2. It now falls back to using the edit-paste from the Adwaita/gnome theme (like other action icons), which is what you see.

The xfce4-clipman package *does* install a symbolic icon:
`/usr/share/icons/hicolor/16x16/apps/clipman-symbolic.svg`

But since the program is actually looking up "clipman" specifically:
https://github.com/xfce-mirror/xfce4-clipman-plugin/blob/master/panel-plugin/main-status-icon.c#L121-L129
it always resorts to edit-paste.

If they changed how they looked up the clipman icon, it would be able to find and use the clipman-symbolic icon without any trouble. But really, they should provide an actual color 'clipman' icon along with a symbolic one. Some themes do already provide one, some don't.

Falling back to an action icon like edit-paste will guarantee *something* usable is always found, but I'm not much of a fan of Gnome's fullcolor style.
