### ISSUE TITLE
Alternative colours for Mint-Y like Mint-X has

### ISSUE THREAD

**Issue by s7jones** [linuxmint/mint-y-icons#7]
See https://github.com/linuxmint/mint-y-theme/issues/11

**Comment by clefebvre** [comment]
This is planned.

**Comment by sviperz** [comment]
Is it still work in progress or is it already implemented through _Customize... > Icons > Mint-Y-**Color**_ selection?

I'm asking because even though folders and other UI elements change their color, the selected item is still green no matter what color theme is selected. Please see the screenshot https://i.imgur.com/Y9JnQjg.png

Is it going to be updated to use a chosen color preset for selected items as well?

Thanks!
